apiVersion: v1
kind: Secret
metadata:
  name: vsphere-credentials
type: kubernetes.io/basic-auth
stringData:
  # Update username/password to vCenter Server credentials
  username: cloudadmin@vmc.local
  password: FILL-ME-IN